project:
  type: website

website:
  title: "Actuarial-Reflections"
  description: "Reflections, projects, and insights by Krishna Shrestha"
  favicon: favicon.ico   # Place your favicon.ico in the project root
  google-analytics: "G-LSZ7YTNKVY"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: all-blogs.qmd
        text: All Blog Posts
      - href: about.qmd
        text: About Me
    right:
      - icon: github
        href: https://github.com/IKSHRESTHA
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/ikshrestha/
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
